app/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

from .views import *

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("logout/", HomeView.as_view(), name="logout"),
    path("login/", HomeView.as_view(), name="login"),
    path("actividad/", ActivityView.as_view(), name="actividad"),
    path("actividades/", ActivityView.as_view(), name="actividades"),
    path("actividades/<int:s>/", ActivityView.as_view(), name="actividades_buscar"),
    path("protocolo/", ProtocolView.as_view(), name="protocolo"),
    path("protocolos/", ProtocolView.as_view(), name="protocolos"),
    path("protocolos/<int:s>/", ProtocolView.as_view(), name="protocolos_buscar"),
    path("proyecto/", ProjectView.as_view(), name="proyecto"),
    path("proyecto/<int:s>/", ProjectView.as_view(), name="proyecto_buscar"),
    path("ejecucion_local/<int:protocol_project>/", LocalExecutionView.as_view(), name="ejecucion_local"),
    path("resolucion_falla/<int:protocol_project>/", FailureResolutionView.as_view(), name="resolucion_falla"),
    path("notificaciones/", NotificationsView.as_view(), name="notificaciones"),
    path("consultas/", InquiriesView.as_view(), name="consultas"),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api-token-auth/", obtain_auth_token, name="api_token_auth"),
    path("get-protocols-by-project/", get_protocols_by_project, name="get_protocols_by_project"),
    path("get-protocol-to-run/", get_protocol_to_run, name="get_protocol_to_run"),
    path("start-processing/", start_processing, name="start_processing"),
    path("set-result-remote-protocol/<int:pk>", set_result_remote_protocol, name="set_result_remote_protocol"),
    path("set-result-project/<int:pk>", set_result_project, name="set_result_project")
]

international_laboratory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext as _


class Activity(models.Model):
    name = models.CharField(_("Nombre"), max_length=150)

    class Meta:
        verbose_name = _("Actividad")
        verbose_name_plural = _("Actividades")
        ordering = ["-id"]

    def __unicode__(self):
        return u"%s" % self.name

    def __str__(self):
        return self.name


class Protocol(models.Model):
    name = models.CharField(_("Nombre"), max_length=150)
    start_date = models.DateTimeField(_("Fecha de inicio"))
    end_date = models.DateTimeField(_("Fecha de fin"))
    order = models.IntegerField(_("Orden de ejecución"), null=False)
    is_local = models.BooleanField(_("Es local"), default=True)
    points = models.FloatField(_("Puntaje necesario"), null=False)
    activities = models.ManyToManyField(Activity, through='ActivityProtocol', verbose_name="Actividades")

    class Meta:
        verbose_name = _("Protocolo")
        verbose_name_plural = _("Protocolos")
        ordering = ["-id"]

    def __unicode__(self):
        return u"%s" % self.name

    def __str__(self):
        return self.name


class ActivityProtocol(models.Model):
    protocol = models.ForeignKey(Protocol, verbose_name="Protocolo", on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, verbose_name="Actividad", on_delete=models.CASCADE)
    approved = models.BooleanField(_("Aprobado"), default=False)

    class Meta:
        verbose_name = _("Actividad en protocolo")
        verbose_name_plural = _("Actividades en protocolo")

    def __unicode__(self):
        return u"%s en %s" % (self.activity, self.protocol)

    def __str__(self):
        return "{} en {}".format(self.activity, self.protocol)


class Project(models.Model):
    name = models.CharField(_("Nombre"), max_length=150)
    start_date = models.DateTimeField(_("Fecha de inicio"))
    end_date = models.DateTimeField(_("Fecha de fin"))
    project_manager = models.CharField(_("Jefe de proyecto"), max_length=10)
    protocols = models.ManyToManyField(Protocol, through='ProtocolProject', verbose_name="Protocolos")
    active = models.BooleanField(_("Activo"), default=True)
    case_id = models.CharField(_("Número de caso"), max_length=5)
    approved = models.BooleanField(_("Aprobado"), blank=True, null=True)

    class Meta:
        verbose_name = _("Proyecto")
        verbose_name_plural = _("Proyectos")
        ordering = ["-id"]

    def __unicode__(self):
        return u"%s" % self.name

    def __str__(self):
        return self.name


class ProtocolProject(models.Model):
    protocol = models.ForeignKey(Protocol, verbose_name="Protocolo", on_delete=models.CASCADE)
    project = models.ForeignKey(Project, verbose_name="Proyecto", on_delete=models.CASCADE)
    result = models.FloatField(_("Resultado"), blank=True, null=True)
    approved = models.BooleanField(_("Aprobado"), blank=True, null=True)
    responsible = models.CharField(_("Responsable"), max_length=10)
    running_task = models.CharField(_("Tarea en ejecución"), max_length=10, blank=True, null=True)

    class Meta:
        verbose_name = _("Protocolo en proyecto")
        verbose_name_plural = _("Protocolo en proyecto")
        ordering = ["approved", "-id"]

    def __unicode__(self):
        return u"%s en %s" % (self.protocol, self.project)

    def __str__(self):
        return "{} en {}".format(self.protocol, self.project)


class Notification(models.Model):
    user_id = models.CharField(_("Destinatario"), max_length=3)
    view = models.BooleanField(_("Leída"), default=False)
    project = models.ForeignKey(Project, verbose_name="Proyecto", on_delete=models.CASCADE)
    protocol = models.ForeignKey(Protocol, verbose_name="Protocolo", blank=True, null=True, on_delete=models.CASCADE)
    need_resolution = models.BooleanField(_("Necesita resolución ante falla"), default=False)
    updated_at = models.DateTimeField(_("Última modificación"), auto_now=True)

    class Meta:
        verbose_name = _("Notificación")
        verbose_name_plural = _("Notificaciones")
        ordering = ["-updated_at", "-id"]

    def __unicode__(self):
        return u"Notificación para %s" % self.user_id

    def __str__(self):
        return "Notificación para {}".format(self.user_id)

    @property
    def protocol_project(self):
        try:
            return ProtocolProject.objects.get(project=self.project, protocol=self.protocol)
        except ProtocolProject.DoesNotExist:
            return None

app/templates/activities_list.html
{% extends "base.html" %}

{% block styles %}
    {% include "datatables_styles.html" %}
{% endblock %}

{% block title %}
    - Listado de actividades
{% endblock %}

{% block content %}
    {% if "Jefe de proyecto" in request.session.user_logged.user_membership %}
        <div class="row justify-content-end">
            <div class="col-4">
                <a href="{% url "actividad" %}"
                   class="btn btn-block btn-secondary-white province-font-bold"
                >
                    Nueva actividad
                </a>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col text-center">
            <h2 class="province-font-black">Actividades</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% if activities %}
                <table id="activities-table"
                       class="display w-100"
                >
                    <thead class="d-none">
                    <tr>
                        <th>ID</th>
                        <th>Actividad</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for activity in activities %}
                        <tr>
                            <td class="d-none">
                                {{ activity.id }}
                            </td>
                            <td>
                                <div class="card my-2">
                                    <div class="card-body">
                                        <h5 class="card-title primary-blue m-0 province-font-medium">
                                            {{ activity.name }}
                                        </h5>
                                    </div>
                                    <div class="accordion"
                                         id="activity-{{ activity.id }}"
                                    >
                                        <div class="card">
                                            <div class="card-header"
                                                 id="activity-{{ activity.id }}-header-1"
                                            >
                                                <button class="btn btn-block text-left province-font-medium"
                                                        type="button"
                                                        data-toggle="collapse"
                                                        data-target="#activity-{{ activity.id }}-data-1"
                                                        aria-expanded="true"
                                                        aria-controls="activity-{{ activity.id }}-data-1">
                                                    Protocolos que la utilizan
                                                </button>
                                            </div>

                                            <div id="activity-{{ activity.id }}-data-1"
                                                 class="collapse show"
                                                 aria-labelledby="activity-{{ activity.id }}-header-1"
                                                 data-parent="#activity-{{ activity.id }}"
                                            >
                                                <div class="card-body">
                                                    {% with activityprotocol=activity.activityprotocol_set.all %}
                                                        {% if activityprotocol %}
                                                            <ul class="list-group">
                                                                {% for ap in activityprotocol %}
                                                                    <li class="list-group-item">
                                                                        <a href="{% url "protocolos_buscar" s=ap.protocol.id %}"
                                                                           class="blue-link"
                                                                        >
                                                                            {{ ap.protocol.name }}
                                                                        </a>
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        {% else %}
                                                            <p class="m-0">
                                                                La actividad no es utilizada por ningún protocolo
                                                            </p>
                                                        {% endif %}
                                                    {% endwith %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Aún no se ha creado ninguna actividad</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {% include "datatables_scripts.html" %}
{% endblock %}

app/templates/create_activity.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    - Crear actividad
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col text-center">
            <h2 class="province-font-black">Crear nueva actividad</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form id="new-activity-form">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col required">
                        <label for="activity-name"
                               class="province-font-medium"
                        >
                            Nombre de la actividad
                        </label>
                        <input type="text"
                               id="activity-name"
                               name="activity-name"
                               class="form-control"
                               placeholder="Completar"
                        >
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col text-right">
                        <button type="button"
                                id="new-activity-submit"
                                class="btn btn-primary-blue province-font-bold">
                            Guardar
                        </button>
                    </div>
                </div>
            </form>
            {% include "alert_error.html" %}
            {% url "actividad" as location %}
            {% include "success_modal.html" with modal_body_text="Se ha creado con éxito la actividad" location_on_close=location %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/create_activity.js" %}"></script>
{% endblock %}

app/templates/local_execution.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    - Ejecución de protocolo local
{% endblock %}

{% block content %}
    <div class="row mb-4">
        <div class="col text-center">
            <h2 class="province-font-black">Informar resultado de actividades</h2>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col">
            <p class="m-0 text-justify">
                A continuación, se deberá indicar las actividades del protocolo <span
                    class="province-font-bold">{{ protocol_project.protocol.name }}</span> del proyecto <span
                    class="province-font-bold">{{ protocol_project.project.name }}</span> que se hayan completado
                correctamente
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form id="local-execution-form">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">
                        <div class="list-group">
                            {% for activity in activities %}
                                <button type="button"
                                        id="activity-item-{{ activity.id }}"
                                        class="my-2 list-group-item list-group-item-action btn-secondary-white"
                                        onclick="updateActivityExecution({{ activity.id }})"
                                >
                                    {{ activity.name }}
                                    <i id="activity-icon-{{ activity.id }}"
                                       class="far fa-circle float-right h4 m-0"
                                    ></i>
                                </button>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col text-right">
                        <button type="button"
                                id="local-execution-submit"
                                class="btn btn-primary-blue province-font-bold">
                            Finalizar
                        </button>
                    </div>
                </div>
            </form>
            {% include "alert_error.html" %}
            {% url "home" as location %}
            {% include "success_modal.html" with modal_body_text="Se ha completado la ejecución local del protocolo" location_on_close=location %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/local_execution.js" %}"></script>
{% endblock %}

app/templates/project_detail.html
{% extends "base.html" %}

{% block title %}
    - Detalle del proyecto {{ project.name }}
{% endblock %}

{% block content %}
    <div class="row mb-4">
        <div class="col text-center">
            <h2 class="province-font-black">Detalle del proyecto</h2>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col text-center">
            <h4 class="province-font-bold">{{ project.name }}</h4>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col">
            <div class="row">
                <div class="col">
                    <h5 class="primary-blue province-font-medium">
                        Protocolos del proyecto
                    </h5>
                </div>
            </div>
            {% for protocolproject in project.protocolproject_set.all %}
                <div class="row">
                    <div class="col">
                        <div class="card my-2">
                            <div class="card-body">
                                <div class="row justify-content-center">
                                    <div class="col">
                                        <p class="card-title m-0 ">
                                            {{ protocolproject.protocol.name }}
                                        </p>
                                    </div>
                                    <div class="col-3 text-center align-self-center">
                                        {% for protocol_project_id, data in state_protocols.items %}
                                            {% if protocol_project_id == protocolproject.id %}
                                                {% if data.state %}
                                                    {% if data.state == "Protocolo aprobado" %}
                                                        <span class="btn-block badge badge-pill bg-success text-white">Aprobado</span>
                                                    {% elif data.state == "En resolución ante falla" %}
                                                        <span class="btn-block badge badge-pill bg-warning text-white">En resolución ante falla</span>
                                                    {% elif data.state == "Protocolo listo para ejecutarse" %}
                                                        <span class="btn-block badge badge-pill bg-primary-blue text-white">Listo para ejecutar</span>
                                                    {% elif data.state == "Protocolo en ejecución" %}
                                                        <span class="btn-block badge badge-pill bg-primary-blue text-white">En ejecución</span>
                                                    {% elif data.state == "El protocolo se encuentra en preparación" %}
                                                        <span class="btn-block badge badge-pill bg-dark text-white">En preparación</span>
                                                    {% elif data.state == "El proyecto se canceló" %}
                                                        <span class="btn-block badge badge-pill bg-danger text-white">Proyecto cancelado</span>
                                                    {% elif data.state == "El proyecto finalizó" %}
                                                        <span class="btn-block badge badge-pill bg-danger text-white">Proyecto finalizado</span>
                                                    {% endif %}
                                                {% else %}
                                                    <span class="btn-block badge badge-pill bg-secondary text-white">No hay información</span>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row mb-5">
        <div class="col">
            <div class="row">
                <div class="col">
                    <h5 class="primary-blue province-font-medium">
                        Estado del proyecto
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="card my-2">
                        <div class="card-body">
                            <div class="row justify-content-center">
                                <div class="col">
                                    <p class="card-title m-0 ">
                                        {% if project.approved %}
                                            <span class="btn-block badge badge-pill bg-success text-white">Proyecto aprobado</span>
                                        {% elif project.approved is False %}
                                            <span class="btn-block badge badge-pill bg-warning text-white">Proyecto no aprobado</span>
                                        {% else %}
                                            {% if task_running.state %}
                                                {% if task_running.state == "failed" %}
                                                    <span class="btn-block badge badge-pill bg-danger text-white">Ejecución fallida</span>
                                                {% else %}
                                                    <span class="btn-block badge badge-pill bg-dark text-white">Proyecto en ejecución</span>
                                                {% endif %}
                                            {% else %}
                                                <span class="btn-block badge badge-pill bg-secondary text-white">No hay información</span>
                                            {% endif %}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/protocols_list.html
{% extends "base.html" %}

{% block styles %}
    {% include "datatables_styles.html" %}
{% endblock %}

{% block title %}
    - Listado de protocolos
{% endblock %}

{% block content %}
    {% if "Jefe de proyecto" in request.session.user_logged.user_membership %}
        <div class="row justify-content-end">
            <div class="col-4">
                <a href="{% url "protocolo" %}"
                   class="btn btn-block btn-secondary-white province-font-bold"
                >
                    Nuevo protocolo
                </a>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col text-center">
            <h2 class="province-font-black">Protocolos</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% if protocols %}
                <table id="protocols-table"
                       class="display w-100"
                >
                    <thead class="d-none">
                    <tr>
                        <th>ID</th>
                        <th>Protocolo</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for protocol in protocols %}
                        <tr>
                            <td class="d-none">
                                {{ protocol.id }}
                            </td>
                            <td>
                                <div class="card my-2">
                                    <div class="card-body">
                                        <h5 class="card-title primary-blue m-0 province-font-medium">
                                            {{ protocol.name }}
                                        </h5>
                                    </div>
                                    <div class="accordion"
                                         id="protocol-{{ protocol.id }}"
                                    >
                                        <div class="card">
                                            <div class="card-header"
                                                 id="protocol-{{ protocol.id }}-header-1"
                                            >
                                                <button class="btn btn-block text-left province-font-medium"
                                                        type="button"
                                                        data-toggle="collapse"
                                                        data-target="#protocol-{{ protocol.id }}-data-1"
                                                        aria-expanded="true"
                                                        aria-controls="protocol-{{ protocol.id }}-data-1">
                                                    Actividades que implementa
                                                </button>
                                            </div>

                                            <div id="protocol-{{ protocol.id }}-data-1"
                                                 class="collapse show"
                                                 aria-labelledby="protocol-{{ protocol.id }}-header-1"
                                                 data-parent="#protocol-{{ protocol.id }}"
                                            >
                                                <div class="card-body">
                                                    {% with activityprotocol=protocol.activityprotocol_set.all %}
                                                        {% if activityprotocol %}
                                                            <ul class="list-group">
                                                                {% for ap in activityprotocol %}
                                                                    <li class="list-group-item">
                                                                        <a href="{% url "actividades_buscar" s=ap.activity.id %}"
                                                                           class="blue-link"
                                                                        >
                                                                            {{ ap.activity.name }}
                                                                        </a>
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        {% else %}
                                                            <p class="m-0">
                                                                El protocolo no implementa ninguna actividad
                                                            </p>
                                                        {% endif %}
                                                    {% endwith %}
                                                </div>
                                            </div>

                                            <div class="card-header"
                                                 id="protocol-{{ protocol.id }}-header-2"
                                            >
                                                <button class="btn btn-block text-left province-font-medium"
                                                        type="button"
                                                        data-toggle="collapse"
                                                        data-target="#protocol-{{ protocol.id }}-data-2"
                                                        aria-expanded="true"
                                                        aria-controls="protocol-{{ protocol.id }}-data-2">
                                                    Proyectos que lo utilizan
                                                </button>
                                            </div>

                                            <div id="protocol-{{ protocol.id }}-data-2"
                                                 class="collapse"
                                                 aria-labelledby="protocol-{{ protocol.id }}-header-2"
                                                 data-parent="#protocol-{{ protocol.id }}"
                                            >
                                                <div class="card-body">
                                                    {% with protocolproject=protocol.protocolproject_set.all %}
                                                        {% if protocolproject %}
                                                            <ul class="list-group">
                                                                {% for pp in protocolproject %}
                                                                    <li class="list-group-item">
                                                                        {{ pp.project.name }}
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        {% else %}
                                                            <p class="m-0">
                                                                El protocolo no es utilizado por ningún proyecto
                                                            </p>
                                                        {% endif %}
                                                    {% endwith %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Aún no se ha creado ningún protocolo</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {% include "datatables_scripts.html" %}
{% endblock %}